// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: multiplayer.proto

package multiplayer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MultiplayerModeService_GetPopularMode_FullMethodName = "/multiplayer.MultiplayerModeService/GetPopularMode"
)

// MultiplayerModeServiceClient is the client API for MultiplayerModeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MultiplayerModeServiceClient interface {
	GetPopularMode(ctx context.Context, in *MultiplayerModeRequest, opts ...grpc.CallOption) (*MultiplayerModeResponse, error)
}

type multiplayerModeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiplayerModeServiceClient(cc grpc.ClientConnInterface) MultiplayerModeServiceClient {
	return &multiplayerModeServiceClient{cc}
}

func (c *multiplayerModeServiceClient) GetPopularMode(ctx context.Context, in *MultiplayerModeRequest, opts ...grpc.CallOption) (*MultiplayerModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MultiplayerModeResponse)
	err := c.cc.Invoke(ctx, MultiplayerModeService_GetPopularMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultiplayerModeServiceServer is the server API for MultiplayerModeService service.
// All implementations must embed UnimplementedMultiplayerModeServiceServer
// for forward compatibility.
type MultiplayerModeServiceServer interface {
	GetPopularMode(context.Context, *MultiplayerModeRequest) (*MultiplayerModeResponse, error)
	mustEmbedUnimplementedMultiplayerModeServiceServer()
}

// UnimplementedMultiplayerModeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMultiplayerModeServiceServer struct{}

func (UnimplementedMultiplayerModeServiceServer) GetPopularMode(context.Context, *MultiplayerModeRequest) (*MultiplayerModeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPopularMode not implemented")
}
func (UnimplementedMultiplayerModeServiceServer) mustEmbedUnimplementedMultiplayerModeServiceServer() {
}
func (UnimplementedMultiplayerModeServiceServer) testEmbeddedByValue() {}

// UnsafeMultiplayerModeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultiplayerModeServiceServer will
// result in compilation errors.
type UnsafeMultiplayerModeServiceServer interface {
	mustEmbedUnimplementedMultiplayerModeServiceServer()
}

func RegisterMultiplayerModeServiceServer(s grpc.ServiceRegistrar, srv MultiplayerModeServiceServer) {
	// If the following call pancis, it indicates UnimplementedMultiplayerModeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MultiplayerModeService_ServiceDesc, srv)
}

func _MultiplayerModeService_GetPopularMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MultiplayerModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiplayerModeServiceServer).GetPopularMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiplayerModeService_GetPopularMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiplayerModeServiceServer).GetPopularMode(ctx, req.(*MultiplayerModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MultiplayerModeService_ServiceDesc is the grpc.ServiceDesc for MultiplayerModeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MultiplayerModeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "multiplayer.MultiplayerModeService",
	HandlerType: (*MultiplayerModeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPopularMode",
			Handler:    _MultiplayerModeService_GetPopularMode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "multiplayer.proto",
}
